spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db2
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
  flyway:
    locations: classpath:db/migrations
  sql:
    init:
      mode: always
server:
  port: 8080