version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: "benit-app-db-dev"
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
  beint-app-api-dev:
    container_name: "benit-app-api-dev"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8080
    depends_on:
      - postgres
    env_file:
      - .env